theme: minima
title: 糖芷的Blog
author: Tang
description: Hello

<h1 data-immersive-translate-walked="30bf0288-c1b6-4e38-88f5-89a3db837887">糖芷的Blog</h1>
![糖芷](/img/TangZhiAll.png)

# 友情链接
friends:
  [
    { title: "BiLiBiLi", href: "http://www.bilibili.com/" },
    { title: "KFC", href: "https://www.kfc.com.cn/" },
  ]
