theme: minima
title: 糖芷TV
author: Tang
description: Hello

# 友情链接
friends:
  [
    { title: "BiLiBiLi", href: "http://www.bilibili.com/" },
    { title: "KFC", href: "https://www.kfc.com.cn/" },
  ]
